/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api'
export * from './configuration'
export * from './model'

import { Configuration } from './configuration'
import {
  AccountsApi,
  AttachmentsApi,
  BudgetingApi,
  CategoriesApi,
  CategoryRulesApi,
  CurrenciesApi,
  EventsApi,
  InstitutionsApi,
  LabelsApi,
  SavedSearchesApi,
  TimeZonesApi,
  TransactionAccountsApi,
  TransactionsApi,
  UsersApi,
} from './api'

export function createPocketSmithApi(pocketSmithApiKey: string) {
  const configuration = new Configuration({ apiKey: pocketSmithApiKey })
  return {
    users: new UsersApi(configuration),
    institutions: new InstitutionsApi(configuration),
    accounts: new AccountsApi(configuration),
    transactionAccounts: new TransactionAccountsApi(configuration),
    transactions: new TransactionsApi(configuration),
    categories: new CategoriesApi(configuration),
    categoryRules: new CategoryRulesApi(configuration),
    budgeting: new BudgetingApi(configuration),
    events: new EventsApi(configuration),
    attachments: new AttachmentsApi(configuration),
    labels: new LabelsApi(configuration),
    savedSearches: new SavedSearchesApi(configuration),
    currencies: new CurrenciesApi(configuration),
    timeZones: new TimeZonesApi(configuration),
  }
}
