/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CurrencySeparators
 */
export interface CurrencySeparators {
    /**
     * The separator used in the major unit.
     * @type {string}
     * @memberof CurrencySeparators
     */
    'major'?: string;
    /**
     * The seperator used for the minor unit.
     * @type {string}
     * @memberof CurrencySeparators
     */
    'minor'?: string;
}

