/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Period
 */
export interface Period {
    /**
     * The start date of the period.
     * @type {string}
     * @memberof Period
     */
    'start_date'?: string;
    /**
     * The end date of the period.
     * @type {string}
     * @memberof Period
     */
    'end_date'?: string;
    /**
     * The currency of the period.
     * @type {string}
     * @memberof Period
     */
    'currency_code'?: string;
    /**
     * The sum of all actuals (transactions) in the period.
     * @type {number}
     * @memberof Period
     */
    'actual_amount'?: number;
    /**
     * The sum of all forecast sources (budget events) in the period, for comparison against the actual amount.
     * @type {number}
     * @memberof Period
     */
    'forecast_amount'?: number;
    /**
     * This attribute tracks the amount that has been refunded or deducted to the actual amount. When a category is set to \"always expense\", any credit transactions are treated as refunds and when set to \"always income\", any debit transactions are treated as deductions.
     * @type {number}
     * @memberof Period
     */
    'refund_amount'?: number;
    /**
     * Whether this period is current, such that the current date (in the user\'s time zone) falls within the date range.
     * @type {boolean}
     * @memberof Period
     */
    'current'?: boolean;
    /**
     * Whether the budget has been exceeded in the period.
     * @type {boolean}
     * @memberof Period
     */
    'over_budget'?: boolean;
    /**
     * Whether the budget has not been exceeded in the period.
     * @type {boolean}
     * @memberof Period
     */
    'under_budget'?: boolean;
    /**
     * How much the budget has been exceeded by in the period.
     * @type {number}
     * @memberof Period
     */
    'over_by'?: number;
    /**
     * How much there is left in the budget for the period.
     * @type {number}
     * @memberof Period
     */
    'under_by'?: number;
    /**
     * The percentage of the budget that has been used in the period.
     * @type {number}
     * @memberof Period
     */
    'percentage_used'?: number;
}

