/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SavedSearch
 */
export interface SavedSearch {
    /**
     * The unique identifier of the saved search.
     * @type {number}
     * @memberof SavedSearch
     */
    'id'?: number;
    /**
     * The title of the saved search.
     * @type {string}
     * @memberof SavedSearch
     */
    'title'?: string;
    /**
     * When the saved search was created.
     * @type {string}
     * @memberof SavedSearch
     */
    'created_at'?: string;
    /**
     * When the saved search was last updated.
     * @type {string}
     * @memberof SavedSearch
     */
    'updated_at'?: string;
}

