/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionsIdAttachmentsPostRequest
 */
export interface TransactionsIdAttachmentsPostRequest {
    /**
     * The unique identifier of the attachment.
     * @type {number}
     * @memberof TransactionsIdAttachmentsPostRequest
     */
    'attachment_id'?: number;
}

