/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AttachmentsIdPutRequest
 */
export interface AttachmentsIdPutRequest {
  /**
   * The new title of the attachment. If the title is blank or not provided, the server will derive a title from the file name.
   * @type {string}
   * @memberof AttachmentsIdPutRequest
   */
  title?: string
}
