/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AttachmentVariants
 */
export interface AttachmentVariants {
    /**
     * The url of the large version of the attachment.
     * @type {string}
     * @memberof AttachmentVariants
     */
    'large_url'?: string;
    /**
     * The url of the thumb version of the attachment.
     * @type {string}
     * @memberof AttachmentVariants
     */
    'thumb_url'?: string;
}

