/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AttachmentContentTypeMeta
 */
export interface AttachmentContentTypeMeta {
  /**
   * The content type title of the attachment.
   * @type {string}
   * @memberof AttachmentContentTypeMeta
   */
  title?: string
  /**
   * The content type description of the attachment.
   * @type {string}
   * @memberof AttachmentContentTypeMeta
   */
  description?: string
  /**
   * The extension type of the attachment.
   * @type {string}
   * @memberof AttachmentContentTypeMeta
   */
  extension?: string
}
