/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CategoriesIdPutRequest
 */
export interface CategoriesIdPutRequest {
  /**
   * A new title for the category.
   * @type {string}
   * @memberof CategoriesIdPutRequest
   */
  title?: string
  /**
   * A new CSS-style hex colour for the category.
   * @type {string}
   * @memberof CategoriesIdPutRequest
   */
  colour?: string
  /**
   * The unique identifier of a parent category for the category, making this category a child of that category.
   * @type {number}
   * @memberof CategoriesIdPutRequest
   */
  parent_id?: number
  /**
   * Set the category as a transfer category.
   * @type {boolean}
   * @memberof CategoriesIdPutRequest
   */
  is_transfer?: boolean
  /**
   * Set the category as a bill category.
   * @type {boolean}
   * @memberof CategoriesIdPutRequest
   */
  is_bill?: boolean
  /**
   * Set the category to be rolled up into its parent category.
   * @type {boolean}
   * @memberof CategoriesIdPutRequest
   */
  roll_up?: boolean
  /**
   * Set the refund behaviour of the category.
   * @type {string}
   * @memberof CategoriesIdPutRequest
   */
  refund_behaviour?: RefundBehaviour | null
}

export const RefundBehaviour = {
  DebitsAreDeductions: 'debits_are_deductions',
  CreditsAreRefunds: 'credits_are_refunds',
} as const

export type RefundBehaviour = (typeof RefundBehaviour)[keyof typeof RefundBehaviour]
