/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InstitutionsIdPutRequest
 */
export interface InstitutionsIdPutRequest {
    /**
     * A new title for the institution.
     * @type {string}
     * @memberof InstitutionsIdPutRequest
     */
    'title'?: string;
    /**
     * A new currency code for the institution.
     * @type {string}
     * @memberof InstitutionsIdPutRequest
     */
    'currency_code'?: string;
}

