/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Category } from './category'
import type { TransactionAccount } from './transaction-account'

/**
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  cheque_number?: string
  /**
   * Whether the transaction is a debit or a credit
   * @type {string}
   * @memberof Transaction
   */
  type?: TransactionType
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  memo?: string
  /**
   * The payee/merchant of the transaction.
   * @type {string}
   * @memberof Transaction
   */
  payee?: string
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  amount?: number
  /**
   * The amount of the transaction in the user\'s base currency.
   * @type {number}
   * @memberof Transaction
   */
  amount_in_base_currency?: number
  /**
   * The date the transaction took place.
   * @type {string}
   * @memberof Transaction
   */
  date?: string
  /**
   * Whether the transaction is a transfer.
   * @type {boolean}
   * @memberof Transaction
   */
  is_transfer?: boolean
  /**
   *
   * @type {Category}
   * @memberof Transaction
   */
  category?: Category
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  note?: string
  /**
   *
   * @type {Array<string>}
   * @memberof Transaction
   */
  labels?: Array<string>
  /**
   * The unique identifier of the transaction.
   * @type {number}
   * @memberof Transaction
   */
  id?: number
  /**
   * The payee the transaction was created with.
   * @type {string}
   * @memberof Transaction
   */
  original_payee?: string
  /**
   * Where the transaction came from.
   * @type {string}
   * @memberof Transaction
   */
  upload_source?: string
  /**
   * The closing balance of the account at the transaction.
   * @type {number}
   * @memberof Transaction
   */
  closing_balance?: number
  /**
   *
   * @type {TransactionAccount}
   * @memberof Transaction
   */
  transaction_account?: TransactionAccount
  /**
   * The status of the transaction. Pending transactions are temporary and may be superseded later by their posted counterparts, which are permanent.
   * @type {string}
   * @memberof Transaction
   */
  status?: Status
  /**
   * Whether the transaction needs to be reviewed.
   * @type {boolean}
   * @memberof Transaction
   */
  needs_review?: boolean
  /**
   * When the transaction was created.
   * @type {string}
   * @memberof Transaction
   */
  created_at?: string
  /**
   * When the transaction was last updated.
   * @type {string}
   * @memberof Transaction
   */
  updated_at?: string
}

export const TransactionType = {
  Debit: 'debit',
  Credit: 'credit',
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]

export const Status = {
  Pending: 'pending',
  Posted: 'posted',
} as const

export type Status = (typeof Status)[keyof typeof Status]
