/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Account } from './account';

/**
 * 
 * @export
 * @interface UsersIdAccountsPutRequest
 */
export interface UsersIdAccountsPutRequest {
    /**
     * List the account objects in their new display order.
     * @type {Array<Account>}
     * @memberof UsersIdAccountsPutRequest
     */
    'accounts': Array<Account>;
}

