/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UsersIdInstitutionsPostRequest
 */
export interface UsersIdInstitutionsPostRequest {
    /**
     * A title for the institution.
     * @type {string}
     * @memberof UsersIdInstitutionsPostRequest
     */
    'title': string;
    /**
     * A currency code for the institution.
     * @type {string}
     * @memberof UsersIdInstitutionsPostRequest
     */
    'currency_code': string;
}

