/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountType } from './account'

/**
 *
 * @export
 * @interface UsersIdAccountsPostRequest
 */
export interface UsersIdAccountsPostRequest {
  /**
   * The ID of the institution to create this account in.
   * @type {number}
   * @memberof UsersIdAccountsPostRequest
   */
  institution_id: number
  /**
   * A title for the account.
   * @type {string}
   * @memberof UsersIdAccountsPostRequest
   */
  title: string
  /**
   * A currency code for the account.
   * @type {string}
   * @memberof UsersIdAccountsPostRequest
   */
  currency_code: string
  /**
   * The type of the account.
   * @type {string}
   * @memberof UsersIdAccountsPostRequest
   */
  type: AccountType
}
