/* tslint:disable */
/* eslint-disable */
/**
 * PocketSmith
 * The PocketSmith API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: api@pocketsmith.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UsersIdCategoriesPostRequest
 */
export interface UsersIdCategoriesPostRequest {
    /**
     * A title for the category.
     * @type {string}
     * @memberof UsersIdCategoriesPostRequest
     */
    'title': string;
    /**
     * A CSS-style hex colour for the category.
     * @type {string}
     * @memberof UsersIdCategoriesPostRequest
     */
    'colour'?: string;
    /**
     * The unique identifier of a category to be the parent of this category.
     * @type {number}
     * @memberof UsersIdCategoriesPostRequest
     */
    'parent_id'?: number;
    /**
     * Set the category as a transfer category.
     * @type {boolean}
     * @memberof UsersIdCategoriesPostRequest
     */
    'is_transfer'?: boolean;
    /**
     * Set the category as a bill category.
     * @type {boolean}
     * @memberof UsersIdCategoriesPostRequest
     */
    'is_bill'?: boolean;
    /**
     * Set the category to be rolled up into its parent category.
     * @type {boolean}
     * @memberof UsersIdCategoriesPostRequest
     */
    'roll_up'?: boolean;
    /**
     * Set the refund behaviour of the category.
     * @type {string}
     * @memberof UsersIdCategoriesPostRequest
     */
    'refund_behaviour'?: RefundBehaviour | null;
}

export const RefundBehaviour = {
    DebitsAreDeductions: 'debits_are_deductions',
    CreditsAreRefunds: 'credits_are_refunds'
} as const;

export type RefundBehaviour = typeof RefundBehaviour[keyof typeof RefundBehaviour];


